# Generated by Django 5.0.4 on 2024-05-09 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_familyevent_id_alter_task_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='calendarapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='calendarapp.familyevent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='calendarapp.user'),
        ),
    ]
