# Generated by Django 5.0.4 on 2024-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_familyevent_end_at_alter_familyevent_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familyevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
