# Generated by Django 5.0.4 on 2024-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_familyevent_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyevent',
            name='crew',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
