# Generated by Django 5.0.4 on 2024-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_personaldates_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldates',
            name='weekdays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
