# Generated by Django 5.0.4 on 2024-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
